<?xml version="1.0"?>
<package format="3">
  <name>agibot_x2_ros2_control</name>
  <version>0.1.0</version>
  <description>ros2_control hardware interface for the AgiBot X2.</description>
  <maintainer email="oscar.ip@lscm.hk">oscar</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>aimdk_msgs</depend>
  <depend>hardware_interface</depend>
  <depend>pluginlib</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>
  <build_depend>pkg-config</build_depend>
  <build_depend>libzmq3-dev</build_depend>
  <exec_depend>libzmq3-dev</exec_depend>
  <exec_depend>python3-zmq</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>rclpy</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
